# Generated by Django 3.1.3 on 2020-12-06 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201206_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_byusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
